#!/bin/bash
#
# starlinkstatus.com probe script
# Author: Manuel Rottschaefer <mail@starlinkstatus.com>
# License: GNU General Public License v3.0

latitude="$1"
longitude="$2"

if [ $# -lt 2 ]
  then
    echo "Please supply latitude and longitude as the first and second parameter, respectively"
    exit 1
fi

report() {
  latency=$(ping -c 3 8.8.8.8 | awk -F '/' 'END {print $5}')
  curl -sL -X POST https://api.starlinkstatus.com/v1/report.php -d "lat=$latitude&lon=$longitude&ping=$latency" > /dev/null
  if [[ -n $VERBOSE ]]; then
    echo "Reported latency ${latency}"
  fi
}

logout() {
  curl -sL -X POST https://api.starlinkstatus.com/v1/logout.php -d "lat=$latitude&lon=$longitude" > /dev/null
  exit 0
}

trap logout TERM
trap logout EXIT

while :
do
  report
  sleep 30
done
